-- =====================================
-- File: 00_schema_overview.sql
-- Purpose: Document the logical data model and table relationships
-- Dataset: Marketing Campaign Performance
-- Tool: Google BigQuery
-- =====================================
